лабораторная работа 3
Bonmagon/PY1 pull request #2
Opened 2022-10-15 10:01 UTC by Bonmagon

Вопросов нет

2022-10-15 13:12 UTC, meat9 requested changes

2022-10-15 13:12 UTC, meat9 commented on лабораторная работа 3/task8.py
> +while money_capital > 0:
Не корректное условие в цикле

2022-10-15 13:12 UTC, meat9 commented on лабораторная работа 3/task8.py
> +print(month - 1)
Подгонка решения под ответ. Это не верно.
Поменяйте условие цикла, а в ответ просто выводите переменную month.
Содержимое цикла написано корректно

2022-10-15 13:12 UTC, meat9 commented on лабораторная работа 3/task9.py
> +    spend = spend * (1 + increase)
Строки можно несколько сократить
    need_money += spend - salary
    spend *= 1 + increase

Это не критично, просто так вы уменьшите кол-во кода

2022-10-15 13:26 UTC, Bonmagon commented on лабораторная работа 3/task9.py
> +    spend = spend * (1 + increase)
хорошо, постараюсь использовать Ваш совет

2022-10-15 13:53 UTC, Bonmagon commented on лабораторная работа 3/task8.py
> +print(month - 1)
Как добавить другое решение? Создавать новый Pull Request?

2022-10-15 14:10 UTC, Bonmagon commented on лабораторная работа 3/task8 v2.py
> +print(month)
так пойдет

2022-10-16 05:20 UTC, meat9 approved these changes

2022-10-16 10:20 UTC, merged